title: "NSE Lab"
#remote_theme: pmarsceill/just-the-docs
theme: "just-the-docs"
color_scheme: "dark"
search_enabled: true
footer_content: "Division of Network and Systems Engineering | KTH" 

defaults:
  -
    scope:
      path: "pages" # empty string for all files
    values:
      layout: "default"